# Generated by Django 5.1.2 on 2024-10-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_citydata_countrydata_locationstore_address_and_more'),
        ('AppEmployee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyHoliday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emer_code', models.CharField(max_length=200, null=True, unique=True)),
                ('emer_name', models.TextField(max_length=200, null=True)),
                ('emer_date', models.DateField(null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_emergency_holiday',
            },
        ),
        migrations.CreateModel(
            name='NationalHoliday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_code', models.CharField(max_length=200, null=True, unique=True)),
                ('holiday_name', models.TextField(max_length=200, null=True)),
                ('holiday_date', models.DateField(null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_national_holiday',
            },
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_role_code', models.CharField(max_length=200, null=True, unique=True)),
                ('sys_role_name', models.TextField(max_length=200, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_system_role',
            },
        ),
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='late_come',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='leave_application_code',
            new_name='leave_app_code',
        ),
        migrations.RenameField(
            model_name='workingschedule',
            old_name='end_time',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workingschedule',
            old_name='shift_description',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='workingschedule',
            old_name='shift_name',
            new_name='work_day_off',
        ),
        migrations.RenameField(
            model_name='workingschedule',
            old_name='start_time',
            new_name='work_day_on',
        ),
        migrations.RenameField(
            model_name='workingschedule',
            old_name='sche_code',
            new_name='work_sche_code',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='work_code',
        ),
        migrations.RemoveField(
            model_name='leavetaken',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='leavetaken',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='leavetaken',
            name='leave_subtype_code',
        ),
        migrations.RemoveField(
            model_name='leavetaken',
            name='leave_type_code',
        ),
        migrations.RemoveField(
            model_name='leavetaken',
            name='to_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='attendance_status',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_sche_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.workingschedule', to_field='work_sche_code'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='late_in',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_category',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_subtype_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.leavesubtype', to_field='leave_subtype_code'),
        ),
        migrations.AddField(
            model_name='leavetaken',
            name='approval_at',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leavetaken',
            name='approval_by',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leavetaken',
            name='leave_app_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.leaveapplication', to_field='leave_app_code'),
        ),
        migrations.AddField(
            model_name='leavetaken',
            name='status',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='break_end_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='break_start_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='break_total_hour',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='end_time_allow',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='loc_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.locationdata', to_field='loc_code'),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='over_time_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='shift_end_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='shift_start_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='shift_total_hour',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='start_time_allow',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='total_allow_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='work_sche_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeepaymentmethod',
            name='account_number',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_code', models.CharField(max_length=100, null=True, unique=True)),
                ('contact_name', models.TextField(max_length=200, null=True)),
                ('contact_relation', models.TextField(max_length=200, null=True)),
                ('mobile_no', models.TextField(max_length=50, null=True)),
                ('alter_mobile_no', models.TextField(max_length=50, null=True)),
                ('home_phone', models.TextField(max_length=50, null=True)),
                ('alter_home_no', models.TextField(max_length=50, null=True)),
                ('work_no', models.TextField(max_length=50, null=True)),
                ('alter_work_no', models.TextField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('employee_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.employee', to_field='employee_code')),
            ],
            options={
                'db_table': 'tbl_emergency_contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=100, null=True)),
                ('last_name', models.TextField(max_length=100, null=True)),
                ('title', models.TextField(max_length=100, null=True)),
                ('mobile', models.TextField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('birth_date', models.DateField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
                ('state', models.TextField(max_length=200, null=True)),
                ('cnic_no', models.TextField(max_length=20, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('remarks', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('employee_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.employee', to_field='employee_code')),
            ],
            options={
                'db_table': 'tbl_employee_format',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('employee_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.employee', to_field='employee_code')),
                ('loc_store_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.locationstore', to_field='loc_store_code')),
            ],
            options={
                'db_table': 'tbl_employee_location',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_hist_code', models.CharField(max_length=200, null=True, unique=True)),
                ('salary_code', models.CharField(max_length=200, null=True)),
                ('pay_frequency', models.TextField(max_length=100, null=True)),
                ('rate_type', models.TextField(max_length=20, null=True)),
                ('rate_amount', models.IntegerField(null=True)),
                ('basic_salary', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('employee_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.employee', to_field='employee_code')),
            ],
            options={
                'db_table': 'tbl_employee_salary_history',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='sys_role_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEmployee.systemrole', to_field='sys_role_code'),
        ),
        migrations.DeleteModel(
            name='WeeklyWorking',
        ),
    ]
