# Generated by Django 5.1.2 on 2024-10-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEmployee', '0002_emergencyholiday_nationalholiday_systemrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='sys_role_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_sche_code',
        ),
    ]
