# Generated by Django 3.2.16 on 2023-04-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.TextField(max_length=200, null=True)),
                ('bank_code', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_bank_data',
            },
        ),
        migrations.CreateModel(
            name='BusinessSector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_sect_code', models.CharField(max_length=100, null=True, unique=True)),
                ('bus_sect_name', models.TextField(max_length=100, null=True)),
                ('status', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_business_sector',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=200, null=True, unique=True)),
                ('company_name', models.TextField(max_length=100, null=True)),
                ('uan_no', models.TextField(max_length=200, null=True)),
                ('ntn_no', models.TextField(max_length=200, null=True)),
                ('strn_no', models.TextField(max_length=200, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('mobile', models.TextField(max_length=200, null=True)),
                ('area', models.TextField(max_length=100, null=True)),
                ('city', models.TextField(max_length=200, null=True)),
                ('state', models.TextField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='Company')),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_company',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_center_code', models.CharField(max_length=200, null=True, unique=True)),
                ('cost_center_name', models.TextField(max_length=100, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_cost_center',
            },
        ),
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bpv_code', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('debit', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('join_code', models.CharField(max_length=100, null=True)),
                ('join_name', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_journal_voucher',
            },
        ),
        migrations.CreateModel(
            name='LineBusiness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_bus_code', models.CharField(max_length=100, null=True, unique=True)),
                ('line_bus_name', models.TextField(max_length=100, null=True)),
                ('status', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_line_business',
            },
        ),
        migrations.CreateModel(
            name='LocationCity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=200, null=True, unique=True)),
                ('city_name', models.TextField(max_length=100, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_location_city',
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_code', models.CharField(max_length=200, null=True, unique=True)),
                ('loc_name', models.TextField(max_length=100, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_location_data',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pm_code', models.CharField(max_length=200, null=True, unique=True)),
                ('pm_name', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_payment_method',
            },
        ),
        migrations.CreateModel(
            name='LocationStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_store_code', models.CharField(max_length=200, null=True, unique=True)),
                ('loc_store_name', models.TextField(max_length=100, null=True)),
                ('status', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('bus_sect_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.businesssector', to_field='bus_sect_code')),
                ('city_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.locationcity', to_field='city_code')),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.company', to_field='company_code')),
                ('cost_center_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.costcenter', to_field='cost_center_code')),
                ('line_bus_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.linebusiness', to_field='line_bus_code')),
                ('loc_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.locationdata', to_field='loc_code')),
            ],
            options={
                'db_table': 'tbl_location_store',
            },
        ),
    ]
